DROP TABLE ISSUE;
DROP TABLE MEMBER;
DROP TABLE BOOKS;
DROP TABLE BOOKS101;
DROP TABLE MEMBER101;
DROP TABLE LIB_ISSUE;
-- SET AUTOCOMMIT OFF;

-- Assignment 01

-- 1
CREATE TABLE MEMBER (
    MEMBER_ID NUMBER(5),
    MEMBER_NAME VARCHAR2(20),
    MEMBER_ADDRESS VARCHAR2(50),
    ACC_OPEN_DATE DATE,
    MEMBERSHIP_TYPE VARCHAR2(20),
    FEES_PAID NUMBER(4),
    MAX_BOOKS_ALLOWED NUMBER(2),
    PENALTY_AMOUNT NUMBER(7, 2)
);

CREATE TABLE BOOKS (
    BOOK_NO NUMBER(6),
    BOOK_NAME VARCHAR2(30),
    AUTHOR_NAME VARCHAR2(30),
    COST NUMBER(7, 2),
    CATEGORY CHAR(10)
);

CREATE TABLE ISSUE (
    LIB_ISSUE_ID NUMBER(10),
    BOOK_NO NUMBER(6),
    MEMBER_ID NUMBER(5),
    ISSUE_DATE DATE,
    RETURN_DATE DATE
);


-- 2
DESC MEMBER;
DESC BOOKS;
DESC ISSUE;


-- 3
DROP TABLE MEMBER;


-- 4
CREATE TABLE MEMBER (
    MEMBER_ID NUMBER(5) PRIMARY KEY,
    MEMBER_NAME VARCHAR2(20),
    MEMBER_ADDRESS VARCHAR2(50),
    ACC_OPEN_DATE DATE,
    MEMBERSHIP_TYPE VARCHAR2(20) CHECK (MEMBERSHIP_TYPE IN ('Lifetime','Annual', 'Half Yearly', 'Quarterly')),
    FEES_PAID NUMBER(4),
    MAX_BOOKS_ALLOWED NUMBER(2),
    PENALTY_AMOUNT NUMBER(7, 2)
);


-- 5
ALTER TABLE MEMBER MODIFY MEMBER_NAME VARCHAR2(30);
DESC MEMBER;

-- 6
ALTER TABLE ISSUE ADD REFERNCE CHAR(30);
DESC ISSUE;

-- 7
ALTER TABLE ISSUE DROP COLUMN REFERNCE;
DESC ISSUE;

-- 8
RENAME ISSUE TO LIB_ISSUE;

-- 9
INSERT INTO MEMBER VALUES (1, 'Richa Sharma', 'Pune', '10-Dec-2025', 'Lifetime', 25000, 5, 50); 
-- PRECISION ERROR
ALTER TABLE MEMBER MODIFY FEES_PAID NUMBER(6);
INSERT INTO MEMBER VALUES (1, 'Richa Sharma', 'Pune', '10-Dec-2025', 'Lifetime', 25000, 5, 50);

INSERT INTO MEMBER VALUES (2, 'Garima Sen', 'Pune', (SELECT CURRENT_DATE FROM DUAL), 'Annual', 1000, 3, NULL);

-- 10
INSERT INTO MEMBER VALUES (3, 'Amit Sharma', 'Bangalore', TO_DATE('2024-06-05', 'YYYY-MM-DD'), 'Quarterly', 1200, 4, 25);
INSERT INTO MEMBER VALUES (4, 'Priya Singh', 'Chennai', TO_DATE('2024-07-20', 'YYYY-MM-DD'), 'Annual', 5000, 10, 0);
INSERT INTO MEMBER VALUES (5, 'Arjun Mehta', 'Kolkata', TO_DATE('2024-09-01', 'YYYY-MM-DD'), 'Half Yearly', 2500, 6, 10);
INSERT INTO MEMBER VALUES (6, 'Neha Verma', 'Hyderabad', TO_DATE('2024-10-15', 'YYYY-MM-DD'), 'Annual', 5000, 10, 0);
INSERT INTO MEMBER VALUES (7, 'Rahul Nair', 'Pune', TO_DATE('2024-11-05', 'YYYY-MM-DD'), 'Quarterly', 1200, 4, 30);


SELECT * FROM MEMBER;

-- 11
ALTER TABLE MEMBER MODIFY MEMBER_NAME VARCHAR2(20); -- NO ERROR, ALL NAMES LENGTH < 20

-- 12
INSERT INTO MEMBER VALUES (1, 'John Sharma', 'Mumbai', '12-Dec-2024', 'Lifetime', 25000, 110, 50); -- PRECISION ERROR


-- 13
CREATE TABLE MEMBER101 AS SELECT * FROM MEMBER;

SELECT * FROM MEMBER101;

-- 14
ALTER TABLE MEMBER ADD CONSTRAINT CHK_MAX_BOOK CHECK (MAX_BOOKS_ALLOWED < 100);
ALTER TABLE MEMBER ADD CONSTRAINT CHK_MAX_PENALTY CHECK (PENALTY_AMOUNT <= 1000);


-- 15
DROP TABLE BOOKS;


-- 16
CREATE TABLE BOOKS (
    BOOK_NO NUMBER(6) PRIMARY KEY,
    BOOK_NAME VARCHAR2(30) NOT NULL,
    AUTHOR_NAME VARCHAR2(30),
    COST NUMBER(7, 2),
    CATEGORY CHAR(10) CHECK (CATEGORY IN ('System', 'Science', 'Fiction', 'Database', 'RDBMS', 'Others'))
);


-- 17
INSERT INTO BOOKS VALUES (101, 'Let us C', 'Denis Ritche', 450, 'System');
INSERT INTO BOOKS VALUES (102, 'Oracle Complete Ref', 'Loni', 550, 'Database');
INSERT INTO BOOKS VALUES (103, 'Mastering SQL', 'Loni', 250, 'Database');
INSERT INTO BOOKS VALUES (104, 'PL SQL Ref', 'Scott Urman', 750, 'Database');

-- 18
INSERT INTO BOOKS VALUES (105, 'Introduction to Databases', 'C. J. Date', 550, 'Database');
INSERT INTO BOOKS VALUES (106, 'Operating System Concepts', 'Silberschatz', 750, 'System');
INSERT INTO BOOKS VALUES (107, 'Brief History of Time', 'Stephen Hawking', 600, 'Science');
INSERT INTO BOOKS VALUES (108, 'The Great Gatsby', 'F. Scott Fitzgerald', 400, 'Fiction');
INSERT INTO BOOKS VALUES (109, 'Learning Oracle RDBMS', 'Thomas Connolly', 680, 'RDBMS');

SELECT * FROM BOOKS;

-- 19
CREATE TABLE BOOK101 AS SELECT * FROM BOOKS WHERE FALSE;
SELECT * FROM BOOK101;

-- 20
INSERT INTO BOOK101 SELECT * FROM BOOKS;

-- 21
COMMIT;


-- 22
SELECT * FROM BOOKS;
SELECT * FROM BOOK101;
SELECT * FROM MEMBERS;


-- 23
INSERT INTO BOOKS VALUES (115, 'National Geographic', 'Adis Scott', 1000, 'Science');

-- 24
ROLLBACK;


-- 25
UPDATE BOOKS SET COST = 300, CATEGORY = 'RDBMS' WHERE BOOK_NO = 103;

-- 26
RENAME LIB_ISSUE TO ISSUE;

-- 27
DROP TABLE ISSUE;

-- 28
CREATE TABLE ISSUE (
    LIB_ISSUE_ID NUMBER(10) PRIMARY KEY,
    BOOK_NO NUMBER(6),
    MEMBER_ID NUMBER(5),
    ISSUE_DATE DATE,
    RETURN_DATE DATE,
    CONSTRAINT FK_ISSUE_BOOK FOREIGN KEY (BOOK_NO) REFERENCES BOOKS(BOOK_NO),
    CONSTRAINT FK_ISSUE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

-- 29
INSERT INTO ISSUE VALUES (7001, 101, 1, '10-Dec-2006', NULL);
INSERT INTO ISSUE VALUES (7002, 102, 2, '26-Dec-2006', NULL);
INSERT INTO ISSUE VALUES (7003, 104, 1, '15-Jan-2006', NULL);
INSERT INTO ISSUE VALUES (7004, 101, 1, '04-Jul-2006', NULL);
INSERT INTO ISSUE VALUES (7005, 104, 2, '15-Nov-2006', NULL);
INSERT INTO ISSUE VALUES (7006, 101, 3, '18-Feb-2006', NULL);

SELECT * FROM ISSUE;

-- 30
COMMIT;

-- 31
ALTER TABLE ISSUE DISABLE PRIMARY KEY;
ALTER TABLE ISSUE DISABLE CONSTRAINT FK_ISSUE_BOOK;
ALTER TABLE ISSUE DISABLE CONSTRAINT FK_ISSUE_MEMBER;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, STATUS FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'ISSUE';

-- 32
SELECT * FROM MEMBER;
INSERT INTO ISSUE VALUES (7006, 101, 99, '18-Feb-2006', NULL); -- 99 MEMBER ID DOES NOT EXIST
-- SUCCESSFULLY INSERTED


-- 33
ALTER TABLE ISSUE ENABLE CONSTRAINT FK_ISSUE_MEMBER;
-- ERROR -> CANNOT VALIDATE, PARENT KEYS NOT FOUND 


-- 34
DELETE FROM ISSUE WHERE MEMBER_ID = 99;
ALTER TABLE ISSUE ENABLE CONSTRAINT FK_ISSUE_MEMBER;

-- 35
DELETE FROM MEMBER WHERE MEMBER_ID = 1;
-- ERROR -> INTEGRITY CONSTRAINT, CHILD RECORD FOUND

-- 36
UPDATE ISSUE SET RETURN_DATE = ISSUE_DATE + 15 WHERE LIB_ISSUE_ID IN (7004, 7005);
SELECT * FROM ISSUE;


-- 37
SELECT * FROM MEMBER;
UPDATE MEMBER SET PENALTY_AMOUNT = 100 WHERE MEMBER_NAME = 'Garima Sen';

-- 38
SAVEPOINT SP1;


-- 39
DELETE FROM ISSUE WHERE MEMBER_ID = 1 AND ISSUE_DATE < TO_DATE('10-DEC-2006');
SELECT * FROM ISSUE;

-- 40
DELETE FROM BOOKS WHERE CATEGORY NOT IN ('RDBMS', 'Database');
SELECT * FROM BOOKS;

-- 41
ROLLBACK TO SP1;


-- 42
ROLLBACK TO SP1;
COMMIT;

-- 43
DROP TABLE MEMBER101;

-- 44
DROP TABLE BOOK101;

-- 45

DESC BOOKS;
DESC MEMBER;
DESC ISSUE;

SELECT * FROM BOOKS;
SELECT * FROM MEMBER;
SELECT * FROM ISSUE;


-- 46
CREATE SEQUENCE NO_SEQ 
    START WITH 100
    INCREMENT BY 2
    MAXVALUE 200
    NOCYCLE;

SELECT NO_SEQ.NEXTVAL FROM DUAL;

-- 47
DROP SEQUENCE NO_SEQ;

-- 48
CREATE SEQUENCE BOOK_SEQ
    START WITH 101
    INCREMENT BY 1
    MAXVALUE 1000
    NOCYCLE;

SELECT BOOK_SEQ.NEXTVAL FROM DUAL;

-- 49
CREATE SEQUENCE MEMBER_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 100
    NOCYCLE;

SELECT MEMBER_SEQ.NEXTVAL FROM DUAL;


-- 50
DROP SEQUENCE BOOK_SEQ;
DROP SEQUENCE MEMBER_SEQ;
